DROP DATABASE IF EXISTS flashcard_app;
CREATE DATABASE flashcard_app;
USE flashcard_app;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS decks;
DROP TABLE IF EXISTS cards;

CREATE TABLE users (
    id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(23) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    user_type ENUM("BASIC", "ADMIN"),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE user_sessions (
    id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    token VARCHAR(255) UNIQUE,
    user_id INT NOT NULL,
    expires_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE decks (
    id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT(1023) NOT NULL,
    user_id INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    visibility ENUM("PRIVATE", "PUBLIC") NOT NULL DEFAULT "PRIVATE",
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE cards (
    id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    term VARCHAR(255) NOT NULL,
    `definition` VARCHAR(255) NOT NULL,
    deck_id INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (deck_id) REFERENCES decks(id)
);